#! /bin/sh
bspc rule -r "*"
##Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends &
feh --bg-scale ~/Downloads/gruvbox.jpg &
killall "polybar"
polybar main &
killall node
node /mnt/Stuff/code/muhbot



bspc monitor -d          
#bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           10
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config top_padding          50

bspc config normal_border_color  "#ffffff"
bspc config active_border_color  "#1bb1b1"
bspc config focused_border_color "#fe8019"
bspc config urgent_border_color "#fe8019"
