#!/usr/bin/env bash

echo "You're about to switch your home-manager configuration as '$USER'"
read -p "Continue (y/n)?" conf

if [[ ${conf,,} =~ ^(y|yes)$ ]]; then
  read -p "Do you want to use sudo instead of doas? (y/n)" conf2
  elev="doas"
  if [[ ${conf2,,} =~ ^(y|yes)$ ]]; then
    elev="sudo"
  fi
  $elev nix build .\#hm-configs.$USER.activationPackage -o hm-result
  ./hm-result/activate
  $elev unlink hm-result
else
  echo "If this is not you, then log into your profile first!"
  exit 1
fi

