# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  fileSystems."/" =
    {
      device = "/dev/disk/by-label/NIXOS_SD";
      fsType = "ext4";
    };

  fileSystems."/nix/store" =
    {
      device = "/nix/store";
      fsType = "none";
      options = [ "bind" ];
    };

  swapDevices = [
    {
      device = "/swapfile";
      priority = 0;
      size = 10240;
    }
  ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
  #hardware.firmware = [ pkgs.raspberrypiWirelessFirmware ];
  hardware.enableRedistributableFirmware = true;
}
